### PR TITLE
Create puzzle2_answer.html

### PR DESCRIPTION
**Pull request by mcfarlandonline**
AHA!

### CODE REVIEW

**Comment by combinatorist** [comment]
Sorry, it looks like you have 2 `s`s in the blue block and 2 `e`s in the purple block. :(

**Comment by mcfarlandonline** [comment]
Arg. This is what I get for continuing on, after dozing off multiple times.

**Comment by combinatorist** [comment]
Haha - been there. :)

Maybe it's TOO methodical.

**Comment by mcfarlandonline** [comment]
I think I updated the file?

**Comment by combinatorist** [comment]
Wow, 9 days ago.  Sorry I didn't see this. I checked and your answer is correct!

**Comment by combinatorist** [comment]
I'm merging it now!

**Comment by mcfarlandonline** [comment]
Huzzah!

**Pull request merged**
