### PR TITLE
I don't know if I'm doing this right...

### PR DESCRIPTION
**Pull request by mcfarlandonline**

### CODE REVIEW

**Comment by combinatorist** [comment]
The only issue I can see is that you need to put a `.html` extension on `puzzle_answer`. :)

**Comment by mcfarlandonline** [comment]
Formalities!
Thanks,

Megan McFarland

  https://netraising.com/
Certified B Corporation®
503-542-4390

**Comment by combinatorist** [comment]
I can't fix the extension because it's on your branch, but once you fix it, I can merge it into the "master". :)

**Comment by mcfarlandonline** [comment]
Did that do it?

**Comment by combinatorist** [comment]
Yes!

**Pull request merged**
